 
// This is an autogenerated file. Editing this will have no effect 
 
const char *build_info_libsexp_name (void) { 
   return "libsexp"; 
} 
 
const char *build_info_libsexp_version (void) { 
   return "0.0.1"; 
} 
 
const char *build_info_libsexp_githash (void) { 
   return "072f26e5aef40f83e58ce4fe6d5d32a2d6ada6fe"; 
} 
 
const char *build_info_libsexp_gitbranch (void) { 
   return "feature/compact"; 
} 
 
const char *build_info_libsexp_target (void) { 
   return "x86_64-linux-gnu"; 
} 
 
const char *build_info_libsexp_targetplatform (void) { 
   return "POSIX"; 
} 
 
const char *build_info_libsexp_hostname (void) { 
   return "Linux"; 
} 
 
const char *build_info_libsexp_ccversion (void) { 
   return "gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0"; 
} 
 
const char *build_info_libsexp_build (void) { 
   return ""; 
} 
 
const char *build_info_libsexp_timestamp (void) { 
   return "1713161582"; 
} 
 
const char *build_info_libsexp_homepage (void) { 
   return "https://github.com/lelanthran/libsexp"; 
} 
