 
// This is an autogenerated file. Editing this will have no effect 
 
#ifndef H_BUILD_INFO_libsexp 
#define H_BUILD_INFO_libsexp 
#ifdef __cplusplus 
extern "C" { 
#endif 
 
   const char *build_info_libsexp_name (void); 
   const char *build_info_libsexp_version (void); 
   const char *build_info_libsexp_githash (void); 
   const char *build_info_libsexp_gitbranch (void); 
   const char *build_info_libsexp_target (void); 
   const char *build_info_libsexp_targetplatform (void); 
   const char *build_info_libsexp_hostname (void); 
   const char *build_info_libsexp_ccversion (void); 
   const char *build_info_libsexp_build (void); 
   const char *build_info_libsexp_timestamp (void); 
   const char *build_info_libsexp_homepage (void); 
 
#ifdef __cplusplus 
}; 
#endif 
 
#endif